export interface EcoAction {
  id: string;
  title: string;
  category: 'travel' | 'home' | 'diet' | 'waste';
  description: string;
  savings: number; // in kg CO2e / year
  effort: 'low' | 'medium' | 'high';
  cost: 'none' | 'low' | 'high';
  impact: 'low' | 'medium' | 'high';
  tip: string;
}

export const ECO_ACTIONS: EcoAction[] = [
  {
    id: 'led-bulbs',
    title: 'Switch to LED Lighting',
    category: 'home',
    description: 'Replace standard incandescent bulbs with energy-efficient LED light bulbs.',
    savings: 150,
    effort: 'low',
    cost: 'low',
    impact: 'low',
    tip: 'LEDs consume up to 85% less energy and last up to 25 times longer than traditional incandescent bulbs.',
  },
  {
    id: 'thermostat-down',
    title: 'Lower Thermostat by 1°C',
    category: 'home',
    description: 'Turn down your heating thermostat by just 1°C during winter months.',
    savings: 300,
    effort: 'low',
    cost: 'none',
    impact: 'medium',
    tip: 'Putting on a sweater instead of cranking the heat can reduce your space heating bill by 10% instantly.',
  },
  {
    id: 'vampire-draw',
    title: 'Eliminate Vampire Power',
    category: 'home',
    description: 'Unplug devices or use smart power strips to cut off idle electricity draw from electronics.',
    savings: 120,
    effort: 'low',
    cost: 'low',
    impact: 'low',
    tip: 'Electronics consume standby power even when turned off. Unplug chargers, TVs, and game consoles when away.',
  },
  {
    id: 'air-dry-laundry',
    title: 'Air-Dry Your Laundry',
    category: 'home',
    description: 'Skip the electric tumble dryer and hang clothes to dry on a line or drying rack.',
    savings: 200,
    effort: 'low',
    cost: 'none',
    impact: 'low',
    tip: 'Tumble dryers are one of the most energy-hungry appliances in the house. Air drying preserves your clothing fabrics longer too.',
  },
  {
    id: 'low-flow-showerhead',
    title: 'Install Low-Flow Showerheads',
    category: 'home',
    description: 'Replace traditional showerheads with modern, aerated low-flow models.',
    savings: 250,
    effort: 'medium',
    cost: 'low',
    impact: 'medium',
    tip: 'This reduces hot water consumption by up to 50% without sacrificing water pressure, saving water and water-heating energy.',
  },
  {
    id: 'green-electricity',
    title: 'Switch to Green Electricity',
    category: 'home',
    description: 'Transition your household utility contract to a 100% certified renewable energy provider.',
    savings: 1200,
    effort: 'medium',
    cost: 'none',
    impact: 'high',
    tip: 'Many providers offer green tariffs at parity or near-parity rates, immediately removing coal/gas generation emissions from your grid draw.',
  },
  {
    id: 'home-insulation',
    title: 'Upgrade Home Insulation',
    category: 'home',
    description: 'Improve loft, wall, or draft insulation to retain heating and cooling energy.',
    savings: 800,
    effort: 'high',
    cost: 'high',
    impact: 'high',
    tip: 'Inadequately insulated homes lose up to 35% of heat through the walls and roof. Good insulation is a lifetime thermal barrier.',
  },
  {
    id: 'heat-pump',
    title: 'Install an Electric Heat Pump',
    category: 'home',
    description: 'Replace an old gas or oil heating furnace with an energy-efficient air-source heat pump.',
    savings: 1800,
    effort: 'high',
    cost: 'high',
    impact: 'high',
    tip: 'Heat pumps are up to 3 to 4 times more efficient than boilers because they move heat rather than generate it through combustion.',
  },
  {
    id: 'walk-bike-short',
    title: 'Walk or Bike Short Trips',
    category: 'travel',
    description: 'Commit to walking or cycling for all personal errands and trips under 3 kilometers.',
    savings: 400,
    effort: 'medium',
    cost: 'none',
    impact: 'medium',
    tip: 'Short car trips are highly carbon-intensive because the engine operates inefficiently before warming up. Great for cardiovascular health!',
  },
  {
    id: 'carpool-commute',
    title: 'Carpool to Work or Study',
    category: 'travel',
    description: 'Share a ride with coworkers or students for your daily commute at least twice a week.',
    savings: 600,
    effort: 'medium',
    cost: 'none',
    impact: 'medium',
    tip: 'By doubling vehicle occupancy, you slash your transport carbon footprint in half and split parking/fuel expenses.',
  },
  {
    id: 'train-over-drive',
    title: 'Take Trains over Driving',
    category: 'travel',
    description: 'Choose intercity rail travel over driving solo for domestic holidays and business trips.',
    savings: 500,
    effort: 'medium',
    cost: 'none',
    impact: 'medium',
    tip: 'Trains emit up to 80% less CO2e per passenger-kilometer compared to solo-driven internal combustion cars.',
  },
  {
    id: 'skip-short-flight',
    title: 'Fly Less (1 Short-Haul Flight)',
    category: 'travel',
    description: 'Reduce flying by substituting one short-haul flight per year with train travel or virtual meetings.',
    savings: 300,
    effort: 'low',
    cost: 'none',
    impact: 'medium',
    tip: 'Aircraft takeoffs require an immense fuel burn. High-altitude emissions also carry greater global warming potential.',
  },
  {
    id: 'skip-long-flight',
    title: 'Fly Less (1 Long-Haul Flight)',
    category: 'travel',
    description: 'Reduce long-haul flights by planning local staycations or conducting digital conferences.',
    savings: 1100,
    effort: 'medium',
    cost: 'none',
    impact: 'high',
    tip: 'A single round-trip long-haul flight can release more carbon than some people generate in an entire year of living.',
  },
  {
    id: 'car-tire-pressure',
    title: 'Maintain Correct Tire Pressure',
    category: 'travel',
    description: 'Check and inflate your car tires to the manufacturer-recommended pressure monthly.',
    savings: 100,
    effort: 'low',
    cost: 'none',
    impact: 'low',
    tip: 'Under-inflated tires increase rolling resistance, which can waste up to 3% of your fuel and cause premature tire wear.',
  },
  {
    id: 'meatless-monday',
    title: 'Adopt "Meatless Mondays"',
    category: 'diet',
    description: 'Avoid meat products entirely one day per week, replacing them with plant-based alternatives.',
    savings: 250,
    effort: 'low',
    cost: 'none',
    impact: 'low',
    tip: 'Livestock production is a major driver of methane emissions and deforestation. Substituting beef with beans saves massive water and land.',
  },
  {
    id: 'go-vegetarian',
    title: 'Transition to Vegetarianism',
    category: 'diet',
    description: 'Adopt a full vegetarian diet, excluding meat, poultry, and seafood.',
    savings: 800,
    effort: 'medium',
    cost: 'none',
    impact: 'high',
    tip: 'Vegetarian diets have around half the carbon footprint of average meat-heavy diets, primarily by eliminating beef and pork.',
  },
  {
    id: 'go-vegan',
    title: 'Adopt a Plant-Based (Vegan) Diet',
    category: 'diet',
    description: 'Eliminate all animal-derived foods from your meals, including dairy, eggs, and gelatin.',
    savings: 1200,
    effort: 'high',
    cost: 'none',
    impact: 'high',
    tip: 'A vegan diet represents the single largest environmental impact reduction you can make on a daily basis regarding food emissions.',
  },
  {
    id: 'eat-local-source',
    title: 'Source Local Food (50%+)',
    category: 'diet',
    description: 'Commit to sourcing at least half of your groceries from local farmers, markets, and regional producers.',
    savings: 150,
    effort: 'medium',
    cost: 'low',
    impact: 'low',
    tip: 'Reduces food miles (transportation fuel) and supports local bio-diverse farming practices that store carbon in topsoil.',
  },
  {
    id: 'meal-plan-zero-waste',
    title: 'Meal Plan to Prevent Food Waste',
    category: 'diet',
    description: 'Plan your weekly meals, prepare shopping lists, and store ingredients properly to eliminate waste.',
    savings: 220,
    effort: 'low',
    cost: 'none',
    impact: 'low',
    tip: 'If food waste were a country, it would be the third-largest emitter of greenhouse gases in the world due to rotting landfill methane.',
  },
  {
    id: 'compost-organic',
    title: 'Compost Organic Waste',
    category: 'waste',
    description: 'Compost fruit scraps, vegetable peelings, coffee grounds, and yard trimmings at home or via municipal bins.',
    savings: 180,
    effort: 'medium',
    cost: 'low',
    impact: 'low',
    tip: 'Composting returns nutrients to soil aerobically. In landfills, organic waste decomposes anaerobically, creating methane gas.',
  },
  {
    id: 'avoid-single-use',
    title: 'Ditch Single-Use Plastics',
    category: 'waste',
    description: 'Replace plastic bags, bottles, and cutlery with reusable equivalents.',
    savings: 100,
    effort: 'low',
    cost: 'none',
    impact: 'low',
    tip: 'Almost all plastic is manufactured from fossil fuels. Refusing single-use items stops supply emissions and prevents ocean microplastics.',
  },
  {
    id: 'thrift-clothing',
    title: 'Buy Clothing Second-Hand',
    category: 'waste',
    description: 'Shop at vintage stores, thrift shops, and online resale platforms instead of buying brand new apparel.',
    savings: 400,
    effort: 'medium',
    cost: 'none',
    impact: 'medium',
    tip: 'The fashion industry is highly resource-intensive. Buying one used item instead of a new garment saves chemical dyes, water, and air miles.',
  },
  {
    id: 'buy-nothing-new-month',
    title: 'Practice a "Buy Nothing New" Month',
    category: 'waste',
    description: 'Spend 30 days purchasing absolutely no new goods, electronics, or clothes, except for fresh food and medicines.',
    savings: 500,
    effort: 'high',
    cost: 'none',
    impact: 'medium',
    tip: 'Breaks consumer impulse loops and makes you appreciate the circular economy by repairing, borrowing, and utilizing what you already have.',
  },
];
